{% set name = "clinfo" %}
{% set version = "3.0.21.02.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Oblomov/clinfo/archive/{{ version }}.tar.gz
  sha256: e52f5c374a10364999d57a1be30219b47fb0b4f090e418f2ca19a0c037c1e694

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx or win]
  run:
    - {{ pin_compatible("ocl-icd") }}  # [linux]
    - {{ pin_compatible("khronos-opencl-icd-loader", max_pin=None) }}  # [osx or win]
test:
  requires:
    - pocl
  commands:
    - clinfo -l

about:
  home: https://github.com/Oblomov/clinfo
  license: CC0-1.0
  license_family: CC
  license_file: legalcode.txt
  summary: 'Print all known information about all available OpenCL platforms and devices in the system'

extra:
  recipe-maintainers:
    - isuruf
